export enum Blockchain {
  BITCOIN = 'Bitcoin',
  LIGHTNING = 'Lightning',
  MONERO = 'Monero',
  ZANO = 'Zano',
  ETHEREUM = 'Ethereum',
  SEPOLIA = 'Sepolia',
  BINANCE_SMART_CHAIN = 'BinanceSmartChain',
  OPTIMISM = 'Optimism',
  ARBITRUM = 'Arbitrum',
  POLYGON = 'Polygon',
  BASE = 'Base',
  GNOSIS = 'Gnosis',
  HAQQ = 'Haqq',
  LIQUID = 'Liquid',
  ARWEAVE = 'Arweave',
  CARDANO = 'Cardano',
  RAILGUN = 'Railgun',
  SOLANA = 'Solana',
  TRON = 'Tron',
  CITREA_TESTNET = 'CitreaTestnet',

  DEFICHAIN = 'DeFiChain',
}
