name: PR CI

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: |
          npm install

      - name: Build code
        run: |
          npx lerna run build

      - name: Run tests
        run: |
          npx lerna run test

      - name: Run linter
        run: |
          npx lerna run lint
