name: Publish packages
on:
  push:
    branches:
      - develop
      - main

env:
  NODE_VERSION: "18.x"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: |
          npm install

      - name: Build code
        run: |
          npx lerna run build

      - name: "Version and publish (beta)"
        if: github.ref == 'refs/heads/develop'
        run: |
          git config user.name "DFX"
          git config user.email "info@dfx.swiss"
          npm config set provenance true

          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes --no-push
          git push origin --tags
          npx lerna publish from-git --yes --dist-tag beta

      - name: "Version and publish (stable)"
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "DFX"
          git config user.email "info@dfx.swiss"
          npm config set provenance true

          npx lerna version --conventional-commits --conventional-graduate --yes --no-push
          git push origin --tags
          npx lerna publish from-git --yes
