name: Publish packages
on:
  push:
    branches:
      - develop
      - main

env:
  NODE_VERSION: "18.x"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: |
          npm install

      - name: Build code
        run: |
          npx lerna run build

      - name: "Version and publish (beta)"
        if: github.ref == 'refs/heads/develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          git config user.name "DFX"
          git config user.email "info@dfx.swiss"

          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          npx lerna publish from-git --yes --dist-tag beta

      - name: "Version and publish (stable)"
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          git config user.name "DFX"
          git config user.email "info@dfx.swiss"

          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from-git --yes

      - name: "Sync main back to develop"
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin develop:develop
          git checkout develop
          git merge main -X theirs -m "chore: sync main into develop after release [skip ci]"
          git push origin develop
